/* eslint-disable prettier/prettier */
export const USER_SET_USER_DATA = 'USER_SET_USER_DATA';
export const USER_SET_AUTH_CHECKED = 'USER_SET_AUTH_CHECKED';

export const BURGER_INGREDIENTS_GET_DATA_SUCCESS = 'BURGER_INGREDIENTS_GET_DATA_SUCCESS';
export const BURGER_INGREDIENTS_GET_DATA_FAILED = 'BURGER_INGREDIENTS_GET_DATA_FAILED';
export const BURGER_INGREDIENTS_SET_ACTIVE_TAB = 'BURGER_INGREDIENTS_SET_ACTIVE_TAB';

export const BURGER_INGREDIENT_DETAILS_SET_DATA = 'BURGER_INGREDIENT_DETAILS_SET_DATA';

export const BURGER_CONSTRUCTOR_RESET_DATA = 'BURGER_CONSTRUCTOR_RESET_DATA';
export const SELECTED_BURGER_INGREDIENTS_ADD_ITEM = 'SELECTED_BURGER_INGREDIENTS_ADD_ITEM';
export const SELECTED_BURGER_INGREDIENTS_DELETE_ITEM = 'SELECTED_BURGER_INGREDIENTS_DELETE_ITEM';
export const REORDER_SELECTED_BURGER_INGREDIENTS = 'REORDER_SELECTED_BURGER_INGREDIENTS';

export const ORDER_DETAILS_MODAL_OPENED_SET_VALUE = 'ORDER_DETAILS_MODAL_OPENED_SET_VALUE';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED = 'MAKE_ORDER_FAILED';
