export const BURGER_INGREDIENTS_SET_DATA = 'BURGER_INGREDIENTS_SET_DATA';
export const BURGER_INGREDIENTS_SET_ACTIVE_TAB = 'BURGER_INGREDIENTS_SET_ACTIVE_TAB';

export const BURGER_INGREDIENT_DETAILS_SET_DATA = 'BURGER_INGREDIENT_DETAILS_SET_DATA';

export const SELECTED_BURGER_INGREDIENTS_ADD_ITEM = 'SELECTED_BURGER_INGREDIENTS_ADD_ITEM';
export const SELECTED_BURGER_INGREDIENTS_DELETE_ITEM = 'SELECTED_BURGER_INGREDIENTS_DELETE_ITEM';
export const REORDER_SELECTED_BURGER_INGREDIENTS = 'REORDER_SELECTED_BURGER_INGREDIENTS';

export const ORDER_DETAILS_SET_DATA = 'ORDER_DETAILS_SET_DATA';