/* eslint-disable prettier/prettier */
export const BURGER_INGREDIENTS_GET_DATA_SUCCESS = 'BURGER_INGREDIENTS_GET_DATA_SUCCESS';
export const BURGER_INGREDIENTS_GET_DATA_FAILED = 'BURGER_INGREDIENTS_GET_DATA_FAILED';
export const BURGER_INGREDIENTS_SET_ACTIVE_TAB = 'BURGER_INGREDIENTS_SET_ACTIVE_TAB';
