/* eslint-disable prettier/prettier */
export const SELECTED_BURGER_INGREDIENTS_RESET_DATA = 'SELECTED_BURGER_INGREDIENTS_RESET_DATA';
export const SELECTED_BURGER_INGREDIENTS_UPDATE_DATA = 'SELECTED_BURGER_INGREDIENTS_UPDATE_DATA';
