/* eslint-disable prettier/prettier */
export const BURGER_CONSTRUCTOR_RESET_DATA = 'BURGER_CONSTRUCTOR_RESET_DATA';
export const SELECTED_BURGER_INGREDIENTS_ADD_ITEM = 'SELECTED_BURGER_INGREDIENTS_ADD_ITEM';
export const SELECTED_BURGER_INGREDIENTS_DELETE_ITEM = 'SELECTED_BURGER_INGREDIENTS_DELETE_ITEM';
export const REORDER_SELECTED_BURGER_INGREDIENTS = 'REORDER_SELECTED_BURGER_INGREDIENTS';

